services:
  node1:
    image: distribuido_node
    networks:
      - kademlia-network
    cap_add:
      - NET_BROADCAST
    ports:
      - "8081:54321"
      - "8091:19009/udp"
    volumes:
      - .:/app

  node2:
    image: distribuido_node
    networks:
      - kademlia-network
    cap_add:
      - NET_BROADCAST
    ports:
      - "8082:54321"
      - "8092:19009/udp"
    volumes:
      - .:/app

  node3:
    image: distribuido_node
    networks:
      - kademlia-network
    cap_add:
      - NET_BROADCAST
    ports:
      - "8083:54321"
      - "8093:19009/udp"
    volumes:
      - .:/app
  node4:
    image: distribuido_node
    networks:
      - kademlia-network
    cap_add:
      - NET_BROADCAST
    ports:
      - "8084:54321"
      - "8094:19009/udp"
    volumes:
      - .:/app
  node5:
    image: distribuido_node
    networks:
      - kademlia-network
    cap_add:
      - NET_BROADCAST
    ports:
      - "8085:54321"
      - "8095:19009/udp"
    volumes:
      - .:/app
  node6:
    image: distribuido_node
    networks:
      - kademlia-network
    cap_add:
      - NET_BROADCAST
    ports:
      - "8086:54321"
      - "8096:19009/udp"
    volumes:
      - .:/app
  node7:
    image: distribuido_node
    networks:
      - kademlia-network
    cap_add:
      - NET_BROADCAST
    ports:
      - "8087:54321"
      - "8097:19009/udp"
    volumes:
      - .:/app
  node8:
    image: distribuido_node
    networks:
      - kademlia-network
    cap_add:
      - NET_BROADCAST
    ports:
      - "8088:54321"
      - "8098:19009/udp"
    volumes:
      - .:/app

  ui:
    image: distribuido_ui
    networks:
      - kademlia-network
    cap_add:
      - NET_BROADCAST
    ports:
      - "8080:54321"
    depends_on:
      - node1
      - node2
      - node3
      - node4
networks:
  kademlia-network:
    external: true
